const API="http://127.0.0.1:5001";let dataset=null;
const $=id=>document.getElementById(id);
function toast(m){$("toast").textContent=m;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",3500)}
function showSection(id){$(id).classList.remove("hidden")}
function payload(){return {target:$("target").value,params:{
decision_tree:{max_depth:+$("dt_depth").value},random_forest:{n_estimators:+$("rf_estimators").value,max_depth:+$("rf_depth").value},
xgboost:{n_estimators:+$("xg_estimators").value,max_depth:+$("xg_depth").value,learning_rate:+$("xg_lr").value,reg_alpha:+$("xg_l1").value,reg_lambda:+$("xg_l2").value},
lightgbm:{n_estimators:+$("lg_estimators").value,max_depth:+$("lg_depth").value,learning_rate:+$("lg_lr").value,lambda_l1:+$("lg_l1").value,lambda_l2:+$("lg_l2").value}}}
function renderInfo(info){$("rows").textContent=info.rows;$("features").textContent=info.features;$("target").innerHTML=info.columns.map(c=>`<option value="${c}">${c}</option>`).join("");if(info.columns.includes("Pass"))$("target").value="Pass";$("preview").innerHTML="<table><thead><tr>"+info.columns.map(c=>`<th>${c}</th>`).join("")+"</tr></thead><tbody>"+info.preview.map(r=>"<tr>"+info.columns.map(c=>`<td>${r[c]??""}</td>`).join("")+"</tr>").join("")+"</tbody></table>";}
async function send(url,body){const r=await fetch(API+url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!j.success)throw Error(j.error||"Request failed");return j}
async function sample(){try{const r=await fetch(API+"/api/upload",{method:"POST"});const j=await r.json();if(!j.success)throw Error(j.error);dataset=j;renderInfo(j.info);$("status").textContent="Sample dataset loaded";}catch(e){$("status").textContent="Backend not running";toast("Start Flask with: python3 backend/app.py")}}
$("sampleBtn").onclick=sample;
$("uploadBtn").onclick=async()=>{const f=$("file").files[0];if(!f)return toast("Choose a CSV first.");try{const fd=new FormData();fd.append("file",f);const r=await fetch(API+"/api/upload",{method:"POST",body:fd});const j=await r.json();if(!j.success)throw Error(j.error);dataset=j;renderInfo(j.info);$("status").textContent=f.name+" loaded";toast("Dataset uploaded successfully.");}catch(e){toast(e.message)}};
$("trainBtn").onclick=async()=>{if(!$("target").value)return toast("Select a target column.");$("trainBtn").disabled=true;$("trainBtn").textContent="Training…";try{const j=await send("/api/train",payload());renderResults(j.results);showSection("results");showSection("diagnostics");showSection("regularization");$("status").textContent=`Trained on ${j.meta.train_rows} rows`;toast("All models trained successfully.");}catch(e){toast(e.message)}finally{$("trainBtn").disabled=false;$("trainBtn").innerHTML='Train All Models <span>→</span>'}};
function renderResults(r){const names=Object.keys(r);$("table").innerHTML=names.map(n=>{let x=r[n];return `<tr><td><b>${n}</b></td><td>${pct(x.train_accuracy)}</td><td>${pct(x.test_accuracy)}</td><td>${pct(x.precision)}</td><td>${pct(x.recall)}</td><td>${pct(x.f1)}</td><td>${pct(x.roc_auc)}</td><td>${pct(x.cv_mean)}</td><td>${x.cv_std.toFixed(3)}</td></tr>`}).join("");
Plotly.newPlot("chart", [{x:names,y:names.map(n=>r[n].train_accuracy),name:"Training",type:"bar"},{x:names,y:names.map(n=>r[n].test_accuracy),name:"Testing",type:"bar"}],{barmode:"group",paper_bgcolor:"transparent",plot_bgcolor:"transparent",font:{color:"#aeb9ca"},yaxis:{range:[0,1],title:"Accuracy"},margin:{t:25,l:50,r:20,b:80}});
const models=names.map(n=>({model:n,train:r[n].train_accuracy,test:r[n].test_accuracy,gap:r[n].gap,status:status(r[n])[0],explanation:status(r[n])[1]}));
Plotly.newPlot("bvchart",[{x:models.map(x=>x.model),y:models.map(x=>x.train),name:"Training",type:"bar"},{x:models.map(x=>x.model),y:models.map(x=>x.test),name:"Testing",type:"bar"}],{barmode:"group",paper_bgcolor:"transparent",plot_bgcolor:"transparent",font:{color:"#aeb9ca"},yaxis:{range:[0,1]},margin:{t:20,l:50,r:10,b:70}});
$("fitcards").innerHTML=models.map(x=>`<div class="fit ${x.status.includes("Over")?"warn":x.status.includes("Under")?"bad":"good"}"><strong>${x.model} · ${x.status}</strong><small>Generalization Gap: ${x.gap.toFixed(3)} · ${x.explanation}</small></div>`).join("");window.lastResults=r}
function pct(x){return (x*100).toFixed(1)+"%"} function status(r){if(r.train_accuracy<.70&&r.test_accuracy<.70)return["Possible Underfitting","Both training and testing performance are relatively low."];if(r.gap>=.10)return["Possible Overfitting","Training accuracy is noticeably higher than testing accuracy."];return["Good Fit","Training and testing performance are reasonably close."]}
$("regBtn").onclick=async()=>{try{const j=await send("/api/regularization",{target:$("target").value,params:{strength:{l1:+$("xg_l1").value||1,l2:+$("xg_l2").value||2}}});const names=Object.keys(j.results),r=j.results;Plotly.newPlot("regchart",[{x:names,y:names.map(n=>r[n].test_accuracy),name:"Test Accuracy",type:"bar"},{x:names,y:names.map(n=>r[n].f1),name:"F1",type:"bar"},{x:names,y:names.map(n=>r[n].roc_auc),name:"ROC-AUC",type:"bar"}],{barmode:"group",paper_bgcolor:"transparent",plot_bgcolor:"transparent",font:{color:"#aeb9ca"},yaxis:{range:[0,1]},margin:{t:20,l:50,r:10,b:70}});$("regtable").innerHTML="<div class='tablewrap'><table><thead><tr><th>Variant</th><th>Train</th><th>Test</th><th>F1</th><th>ROC-AUC</th><th>Gap</th></tr></thead><tbody>"+names.map(n=>`<tr><td>${n}</td><td>${pct(r[n].train_accuracy)}</td><td>${pct(r[n].test_accuracy)}</td><td>${pct(r[n].f1)}</td><td>${pct(r[n].roc_auc)}</td><td>${r[n].gap.toFixed(3)}</td></tr>`).join("")+"</tbody></table></div>"}catch(e){toast(e.message)}}
const concepts=[["Bagging","Trains models on varied bootstrap samples and combines their predictions."],["Boosting","Builds models sequentially so later learners focus on previous errors."],["Random Forest","A bagging ensemble of randomized decision trees."],["XGBoost","A gradient-boosting implementation with strong regularization controls."],["LightGBM","A fast gradient-boosting framework designed for efficient tree learning."],["Bias","Error from a model being too simple to capture useful patterns."],["Variance","Sensitivity to training data; high variance often appears as overfitting."],["Overfitting","Training performance is high but testing performance falls noticeably."],["Underfitting","The model is too simple, giving low training and testing performance."],["L1 Regularization","Adds an absolute-weight penalty; in XGBoost this is reg_alpha."],["L2 Regularization","Adds a squared-weight penalty; in XGBoost this is reg_lambda."],["Model Evaluation","Accuracy, precision, recall, F1, ROC-AUC and cross-validation summarize performance."]];
$("concepts").innerHTML=concepts.map(c=>`<div class="concept"><b>${c[0]}</b><span>${c[1]}</span></div>`).join("");sample();
